Indirectly construct GEPArg from int32_t
GEPArg is essentially a wrapper around union of int32_t and mlir::Value.
Explicitly cast other types (e.g. unsigned) to int32_t to avoid
narrowing conversion warnings on MSVC. In particular:

llvm-project\mlir\lib\Dialect\LLVMIR\Transforms\TypeConsistency.cpp(496):
error C2398: Element '1': conversion from 'size_t' to 'T' requires a
narrowing conversion
    with
    [
        T=mlir::LLVM::GEPArg
    ]

llvm-project\mlir\lib\Dialect\LLVMIR\Transforms\TypeConsistency.cpp(534):
error C2398: Element '1': conversion from 'unsigned int' to 'T' requires a
narrowing conversion
    with
    [
        T=mlir::LLVM::GEPArg
    ]